[package]
name = "sqs_wrapper"
version = "0.1.0"
authors = ["Niclas Rosengren <niclas.rosengren@gmail.com>"]

[dependencies]
futures = "0.1"
rusoto_core = "0.35"
rusoto_sqs = "0.35"
log = "0.4"


[dev-dependencies]
tokio = "0.1"
rusoto_credential = "0.14"
